github:
  description: "Apache CXF website"
  homepage: https://cxf.apache.org/

staging:
  profile: ~
  whoami:  asf-staging


notifications:
  commits: commits@cxf.apache.org
  issues: issues@cxf.apache.org
  pullrequests: dev@cxf.apache.org
