github:
  description: "Apache CXF website"
  homepage: https://cxf.apache.org/

  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
staging:
  profile:
  whoami: asf-staging


notifications:
  commits: commits@cxf.apache.org
  issues: issues@cxf.apache.org
  pullrequests: dev@cxf.apache.org
